#pragma once
#include "GLFW/glfw3.h"
#include <glm.hpp>
#include <gtc/matrix_transform.hpp>

#include <iostream>
#include <sstream>
#include <fstream>
#include <unordered_map>
#include <string>
#include <memory>
#include <functional>
#include "bq/math/vec.hpp"
#include "bq/graphics/texture.hpp"
#include "bq/graphics/index_buffer.hpp"
#include "bq/graphics/vertex_buffer.hpp"
#include "bq/graphics/vertex_buffer_layout.hpp"
#include "bq/graphics/vertex_array.hpp"
#include "bq/graphics/shader.hpp"
#include "bq/graphics/gl_renderer_2d.hpp"
#include "bq/graphics/window.hpp"